spring.application.name=SpringMVC

# Puerto del servidor (opcional)
# Puerto del servidor
server.port=${PORT:8080}
# Configuracion de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d6p8ggh4tr6s73aijlrg-a.frankfurt-postgres.render.com:5432/pelis-db
spring.datasource.username=postgresdb_p9ns_user
spring.datasource.password=WTCYwls0KCtnjEkb8DcObfgmnduw9r07
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Log del Hikari (pool de conexiones)
logging.level.com.zaxxer.hikari=INFO

# Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
